// React imports
import React from 'react';
import { Link } from 'react-router-dom';

// Redux imports

// Components
import Spinner from '../layoutComponents/Spinner';

// Styles and Images
import {
  Container,
  Row,
  Col,
  Dropdown,
  DropdownButton,
  ButtonGroup,
  Button,
} from 'react-bootstrap';


const PostItem = () => {
  return (
    <>
    {/* Forum item heading */}
    <Container>
        <Row className="forumHeadings">
            <Col xs={12} className="forumCol">
                <h4>How do I record Hypolliope? <p>(this heading will be generated by user question)</p></h4>
            </Col>          
        </Row>
    </Container>

    <br />

    {/* Forum item postings */}
    <Container>
        <Row className="forumRow">
            <Col xs={2} className="forumCol">user-name-of-original-posting</Col>
            <Col xs={10} className="forumCol">
                <Col xs={12} style={{ borderBottom: "solid", borderBottomStyle: "groove", borderColor: "#c0c0c0" }}>auto-generated date/time</Col>
                <br></br>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus neque nec neque efficitur ultricies.
                Morbi non leo at nunc semper congue non ut leo. Etiam suscipit tempus mauris, a viverra ipsum ullamcorper vitae. 
                Curabitur facilisis feugiat egestas. Sed ullamcorper convallis cursus. Suspendisse ut dignissim neque. Vestibulum non pretium magna.</p>
            </Col>       
        </Row>
      
        <br />
    
        <Row className="forumRow">
            <Col xs={2} className="forumCol">name-of-first-responding-user</Col>
            <Col xs={10} className="forumCol">
                <Col xs={12} style={{ borderBottom: "solid", borderBottomStyle: "groove", borderColor: "#c0c0c0" }}>auto-generated date/time</Col>
                <br></br>
                <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
                    Aliquam convallis, turpis quis posuere auctor, mauris dui ultricies enim, sed volutpat mi tellus bibendum sem.</p>
            </Col>          
        </Row>
        <Row className="forumRow">
            <Col xs={2} className="forumCol">name-of-second-responding-user</Col>
            <Col xs={10} className="forumCol">
                <Col xs={12} style={{ borderBottom: "solid", borderBottomStyle: "groove", borderColor: "#c0c0c0" }}>auto-generated date/time</Col>
                <br></br>
                <p>Donec gravida at erat sed accumsan. Nam vitae posuere eros, eget blandit magna. Curabitur sed nisi nec tellus malesuada semper a ut enim. 
                    Nulla id lacinia tellus. Vestibulum blandit accumsan massa at dapibus.</p>
            </Col>          
        </Row>
    </Container>
    
    </>
    );
  };

  export default PostItem;
